# Generated by Django 2.1.7 on 2023-09-03 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.CharField(max_length=400)),
                ('short_url', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
